### ISSUE TITLE
TODO before FENS

### ISSUE THREAD

**Issue by clewis7** [fastplotlib/fastplotlib#512]
- [x] #511 
- [x] rebase and merge #509 
     - [x] remove nbs and just have examples in gallery
     - [x] remove quickstart guide (all examples in gallery)
     - [x] refactor examples to use `figure` instead of `fig`, remove `canvas = fig.canvas` declarations
     - [x] add more examples (events, animations, etc.)
- [x] #510 
- [x] release :D
- [x] test that everything on this new fpl release works with current releases of `pygfx` and `wgpu` on pypi
